development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ebooktedb_development
  pool: 5
  username: rails_user
  password: mint06

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ebooktedb_test
  pool: 5
  username: rails_user
  password: mint06

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ebooktedb_production
  pool: 5
  username: rails_user
  password: mint06 